---
- hosts: localhost
  gather_facts: no
  vars_files:
  - /root/default_vars.yml
  - /root/aws_saml_cert.yml
  tasks:
  - include_vars:
      file: "{{ item.file }}"
      name: "{{ item.name }}"
    with_items:
      - name: saml2_sso_configdata
        file: /secrets/configdata.yml
      - name: saml2_sso_authdata
        file: /secrets/authdata.yml

  - file:
      path: "/configdata/{{item}}"
      state: directory
      mode: 0700
      owner: user
      group: group
    with_items:
    - ssh
    - certs

  - name: populate templated config files
    template:
      src: "/root/templates/{{ item }}.j2"
      dest: "/configdata/{{ item }}"
      owner: user
      group: root
      mode: 0600
    with_items:
      - config.php
      - saml20-idp-hosted.php
      - saml20-sp-remote.php
      - ssl.conf
      - google_api_client_secrets.json
      - authsources.php

  - name: check if original ssl.conf exists
    stat: path=/etc/httpd/conf.d/ssl.conf
    register: ssl_conf_stat_result

  - name: save original ssl.conf config
    command: mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.orig
    when: 'ssl_conf_stat_result.stat.isreg == True'

  - name: symlink to authdata.yml
    file:
      src: "/secrets/{{ saml2_sso_configdata.authdata_path | basename }}"
      dest: "{{ saml2_sso_configdata.authdata_path }}"
      state: link

  - name: symlink to populated config files
    file:
      src: "/configdata/{{ item.name }}"
      dest: "{{ item.path }}{{ item.name }}"
      state: link
    with_items:
      - name: config.php
        path: /etc/simplesamlphp/
      - name: saml20-idp-hosted.php
        path: /etc/simplesamlphp/metadata/
      - name: saml20-sp-remote.php
        path: /etc/simplesamlphp/metadata/
      - name: ssl.conf
        path: /etc/httpd/conf.d/
      - name: authsources.php
        path: /etc/simplesamlphp/

  - name: install authorized_keys file
    copy:
      src: /secrets/authorized-keys
      dest: /configdata/ssh/authorized_keys
      owner: user
      group: group
      mode: 0600

  - name: install ssh host keys
    copy:
      content: "{{ item.value }}"
      dest: "/configdata/ssh/{{ item.key }}"
      owner: user
      group: root
      mode: 0400
    no_log: True
    with_dict: "{{ saml2_sso_configdata.ssh_keys }}"

  - file:
      src: /configdata/certs
      dest: "{{ saml2_sso_configdata.certdir | dirname }}"
      state: link

  - name: install IdP SSL Cert/Key
    copy:
      content: "{{ item.content }}"
      dest: "/configdata/certs/{{ item.name }}"
      owner: user
      group: root
      mode: 0400
    no_log: True
    with_items:
      - name: "{{ saml2_sso_configdata.saml_cert_file }}"
        content: "{{ saml2_sso_configdata.saml2_idp_cert_data.cert }}"
      - name: "{{ saml2_sso_configdata.saml_privatekey_file }}"
        content: "{{ saml2_sso_configdata.saml2_idp_cert_data.key }}"

  # NOTE: this must be the final task because it indicates to
  #       the start-up script that this playbook successfully
  #       ran to completion.
  - name: touch file to indicate that the reconfigure was successful
    copy:
      content: ""
      dest: "{{ config_success_touchfile }}"
