---
galaxy_info:
  author: OpenShift Ops
  description: Openshift Operations Master Audit Config
  company: Red Hat, Inc
  license: ASL 2.0
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 7
dependencies:
- role: tools_roles/lib_repoquery
- role: tools_roles/lib_yaml_editor
