---
g_default_zagg_server_config:
  targets:
  - name: local cluster zbx server
    type: zabbix
    trapper_server: oso-rhel7-zabbix-server
    trapper_port: 10051
    api_url: http://oso-rhel7-zabbix-web/zabbix/api_jsonrpc.php
    api_user: apiuser
    api_password: apipass
    path: /var/run/zagg/data/local-cluster-zbx

g_default_zagg_server_user: zagg-user
g_default_zagg_server_password: zagg-password
