---
obg_output_path: /tmp
obg_registry_template: openshift3/ose-${component}:${version}
obg_install_registry_console: false
obg_install_web_console: false
obg_install_ansible_service_broker: false
obg_install_openshift_service_catalog: false
obg_install_template_service_broker: false
obg_install_openshift_prometheus: false
obg_install_openshift_management: false
obg_install_metrics: false
obg_install_logging: false
obg_inventory_sdn: redhat/openshift-ovs-networkpolicy
obg_master_cluster_hostname: internal.api.example.com
obg_master_public_hostname: api.example.com
obg_master_public_api_url: https://api.example.com
obg_master_public_console_url: https://console.example.com/console
obg_router_domain: apps.example.com
obg_custom_cors_origins: [ 'console.example.com', 'api.example.com' ]
obg_install_router: False
obg_install_registry: False
obg_cluster_network_cidr: False
obg_master_portal_net: False
obg_logging_variables: {}
obg_metrics_variables: {}
obg_ip_choice: oo_public_ip
obg_use_private_ips: False
