---
- name: Install needed RPMs
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - openshift-tools-scripts-inventory-clients
  - openshift-tools-scripts-monitoring

- file:
    state: directory
    dest: /etc/ansible/inventory
    owner: root
    group: libra_ops
    mode: 0750

- file:
    state: link
    src: /usr/share/ansible/inventory/multi_inventory.py
    dest: /etc/ansible/inventory/multi_inventory.py
    owner: root
    group: libra_ops

- block:

    - name: stat multi_inventory.log
      stat:
        path: /var/log/multi_inventory.log
      register: multi_stat

    - name: touch log file when doesn't exist
      command: /usr/bin/touch /var/log/multi_inventory.log
      when: not multi_stat.stat.exists

    - name: set file permissions on multi_inventory.log
      file:
        path: /var/log/multi_inventory.log
        owner: root
        group: libra_ops
        mode: 0660

    - name: copy inventory.sh into place
      template:
        src: templates/inventory.sh.j2
        dest: /usr/local/bin/inventory.sh
        owner: root
        group: libra_ops
        mode: 0750

    - name: copy ssh key for rsync in place
      copy:
        content: "{{ oo_rsync_private_key }}"
        dest: "/root/.ssh/rsync_inventory_cache_key"
        owner: root
        group: root
        mode: 0600
      when: oo_rsync_private_key is defined

    - name: setup known_hosts
      include_tasks: known_hosts.yml
      with_items: "{{ oo_rsync_cache_targets }}"
      when: oo_rsync_cache_targets is defined

    # This cron uses the above location to call its job
    - name: Cron to keep cache fresh
      cron:
        name: 'multi_inventory'
        minute: '*/10'
        job: '/usr/bin/ops-runner -n cmirc.multi_inventory.refresh -t 120 /usr/local/bin/inventory.sh &> /dev/null'

    - name: Cron to update cache on reboot
      cron:
        name: 'multi_inventory at reboot'
        job: '/usr/bin/ops-runner -n cmirc.multi_inventory.refresh -t 120 /usr/local/bin/inventory.sh &> /dev/null'
        special_time: reboot

  when: oo_cron_refresh_cache is defined and oo_cron_refresh_cache

- name: Set cache location
  file:
    state: directory
    dest: "{{ oo_inventory_cache_location | dirname }}"
    owner: root
    group: libra_ops
    recurse: yes
    mode: '2775'
  when: oo_inventory_cache_location is defined
