---
- name: ensure chrony and ntp package is installed
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
  - chrony
  - ntp

- name:
  service:
    name: ntpd
    state: stopped
    enabled: no

- name: ensure chrony package is installed
  yum:
    name: chrony
    state: installed

- name: Install /etc/chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart chronyd

- name: enabled timedatectl set-ntp yes
  timedatectl:
    ntp: True

- name:
  service:
    name: chronyd
    state: started
    enabled: yes
