---
g_template_openshift_cluster:
  name: Template OpenShift Cluster
  zitems:
  - key: openshift.cluster.configloop.exitcode
    applications:
    - OpenShift Cluster
    value_type: int

  - key: openshift.cluster.configloop.runtime
    applications:
    - OpenShift Cluster
    value_type: int

  ztriggers:
  - name: "Config loop failed on {HOST.NAME}"
    expression: "{Template OpenShift Cluster:openshift.cluster.configloop.exitcode.min(#3)}>0"
    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/check_config_loop.asciidoc"
    priority: high

  zdiscoveryrules:
  - name: disc.openshift.cluster.router
    key: disc.openshift.cluster.router
    lifetime: 14
    description: "Hold cluster-wide dynamic router items"

  zitemprototypes:
  - discoveryrule_key: disc.openshift.cluster.router
    name: "{% raw %}OpenShift router health [{{ '{#' }}OS_ROUTER}]{% endraw %}"
    key: "{% raw %}disc.openshift.cluster.router.health[{{ '{#' }}OS_ROUTER}]{% endraw %}"
    value_type: int
    description: "Health of OpenShift router"
    applications:
    - OpenShift Cluster

  - discoveryrule_key: disc.openshift.cluster.router
    name: "{% raw %}OpenShift router expected POD count [{{ '{#' }}ROUTER_DC}]{% endraw %}"
    key: "{% raw %}disc.openshift.cluster.router.expected_pod_count[{{ '{#' }}ROUTER_DC}]{% endraw %}"
    value_type: int
    description: "Whether number of running router PODs matches definition in deployment config"
    applications:
    - OpenShift Cluster


  ztriggerprototypes:
  - name: "{% raw %}Router: {{ '{#' }}OS_ROUTER} is failing health checks{% endraw %}"
    expression: "{% raw %}{Template OpenShift Cluster:disc.openshift.cluster.router.health[{{ '{#' }}OS_ROUTER}].max(#3)}<1{% endraw %}"
    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/openshift_router.asciidoc"
    priority: average

  - name: "{% raw %}Router: {{ '{#' }}ROUTER_DC} has unexpected number of running PODs{% endraw %}"
    expression: "{% raw %}{Template OpenShift Cluster:disc.openshift.cluster.router.expected_pod_count[{{ '{#' }}ROUTER_DC}].max(#3)}<1{% endraw %}"
    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/openshift_router.asciidoc"
    priority: average
