---
g_template_logging:
  name: Template OpenShift Logging

  zitems:
  - key: openshift.logging.fluentd.running
    applications:
    - EFK
    value_type: int
  - key: openshift.logging.fluentd.number_pods
    applications:
    - EFK
    value_type: int
  - key: openshift.logging.fluentd.node_mismatch
    applications:
    - EFK
    value_type: int
  - key: openshift.logging.fluentd.number_expected_pods
    applications:
    - EFK
    value_type: int
  - key: openshift.logging.fluentd.queue.oldest
    applications:
    - EFK
    value_type: int
  - key: openshift.logging.kibana.site_up
    applications:
    - EFK
    value_type: int
  - key: openshift.logging.kibana.response_code
    applications:
    - EFK
    value_type: int
  - key: openshift.logging.elasticsearch.single_master
    applications:
    - EFK
    value_type: int
  - key: openshift.logging.elasticsearch.all_numbers_registered
    applications:
    - EFK
    value_type: int

  ztriggers:
  - name: "ElasticSearch is in split brain on {HOST.NAME}"
    expression: "{Template OpenShift Logging:openshift.logging.elasticsearch.single_master.last()}=0"
    url: "https://github.com/openshift/ops-sop/blob/master/v3/alerts/elasticsearch.asciidoc"
    priority: high
  - name: "FluentD/Node pod number mismatch on {HOST.NAME}"
    expression: "{Template OpenShift Logging:openshift.logging.fluentd.number_pods.last()}<>{Template OpenShift Logging:openshift.logging.fluentd.number_expected_pods.last()}"
    url: "https://github.com/openshift/ops-sop/blob/master/v3/alerts/fluentd.asciidoc"
    priority: warning
  - name: "FluentD/Node mismatch on {HOST.NAME}"
    expression: "{Template OpenShift Logging:openshift.logging.fluentd.node_mismatch.last()}<>0"
    url: "https://github.com/openshift/ops-sop/blob/master/v3/alerts/fluentd.asciidoc"
    priority: warning
  - name: "kibana not working on {HOST.NAME}"
    expression: "{Template OpenShift Logging:openshift.logging.kibana.site_up.last()}<>1"
    url: "https://github.com/openshift/ops-sop/blob/master/v3/alerts/check_logging.asciidoc#kibana"
    priority: high

  zdiscoveryrules:
  - name: openshift.logging.elasticsearch.pods
    key: openshift.logging.elasticsearch.pods
    lifetime: 7
    description: "Elasticsearch pods"

  zitemprototypes:
  - discoveryrule_key: openshift.logging.elasticsearch.pods
    name: "{% raw %}openshift.logging.elasticsearch.pod_health.{{ '{#' }}OSO_METRICS}{% endraw %}"
    key: "{% raw %}openshift.logging.elasticsearch.pod_health[{{ '{#' }}OSO_METRICS}]{% endraw %}"
    value_type: int
    description: "elasticsearch pod health status"
    applications:
    - EFK
  - discoveryrule_key: openshift.logging.elasticsearch.pods
    name: "{% raw %}openshift.logging.elasticsearch.disk_free_pct.{{ '{#' }}OSO_METRICS}{% endraw %}"
    key: "{% raw %}openshift.logging.elasticsearch.disk_free_pct[{{ '{#' }}OSO_METRICS}]{% endraw %}"
    value_type: int
    description: "elasticsearch pv free space"
    applications:
    - EFK
  - discoveryrule_key: openshift.logging.elasticsearch.pods
    name: "{% raw %}openshift.logging.elasticsearch.pod_active_primary_shards.{{ '{#' }}OSO_METRICS}{% endraw %}"
    key: "{% raw %}openshift.logging.elasticsearch.pod_active_primary_shards[{{ '{#' }}OSO_METRICS}]{% endraw %}"
    value_type: int
    description: "elasticsearch pod active primary shards "
    applications:
    - EFK
  - discoveryrule_key: openshift.logging.elasticsearch.pods
    name: "{% raw %}openshift.logging.elasticsearch.pod_pending_task_queue_depth.{{ '{#' }}OSO_METRICS}{% endraw %}"
    key: "{% raw %}openshift.logging.elasticsearch.pod_pending_task_queue_depth[{{ '{#' }}OSO_METRICS}]{% endraw %}"
    value_type: int
    description: "elasticsearch pod pending task queue depth"
    applications:
    - EFK

  ztriggerprototypes:
  - name: "{% raw %}Logging: {{ '{#' }}OSO_METRICS} ES Cluster disk free is too low  {HOST.NAME}{% endraw %}"
    expression: "{% raw %}({TRIGGER.VALUE}=0 and {Template OpenShift Logging:openshift.logging.elasticsearch.disk_free_pct[{{ '{#' }}OSO_METRICS}].last()}<13) or ({TRIGGER.VALUE}=1 and {Template OpenShift Logging:openshift.logging.elasticsearch.disk_free_pct[{{ '{#' }}OSO_METRICS}].last()}<19){% endraw %}"
    url: "https://github.com/openshift/ops-sop/blob/master/v3/alerts/check_logging.asciidoc"
    priority: high
  - name: "{% raw %}Logging: {{ '{#' }}OSO_METRICS} ES Cluster disk free is critical low {HOST.NAME}{% endraw %}"
    expression: "{% raw %}({TRIGGER.VALUE}=0 and {Template OpenShift Logging:openshift.logging.elasticsearch.disk_free_pct[{{ '{#' }}OSO_METRICS}].last()}<8) or ({TRIGGER.VALUE}=1 and {Template OpenShift Logging:openshift.logging.elasticsearch.disk_free_pct[{{ '{#' }}OSO_METRICS}].last()}<13){% endraw %}"
    url: "https://github.com/openshift/ops-sop/blob/master/v3/alerts/check_logging.asciidoc"
    priority: high

  - name: "{% raw %}Logging: {{ '{#' }}OSO_METRICS} ES Cluster health is critical in RED state on {HOST.NAME}{% endraw %}"
    expression: "{% raw %}{Template OpenShift Logging:openshift.logging.elasticsearch.pod_health[{{ '{#' }}OSO_METRICS}].max(#3)}<1{% endraw %}"
    url: "https://github.com/openshift/ops-sop/blob/master/v3/alerts/check_logging.asciidoc"
    priority: high
