---
- hosts: localhost
  gather_facts: no
  vars_files:
  - /root/default_vars.yml
  vars:
    g_zagg_client_config:
      host:
        name: "{{ lookup('env', 'ZAGG_CLIENT_HOSTNAME') | default(g_default_zagg_client_hostname, True) }}"
      zagg:
        host: "{{ lookup('env', 'ZAGG_SERVER') | default(g_default_zagg_server, True) }}"
        user: "{{ lookup('env', 'ZAGG_USER') | default(g_default_zagg_user, True) }}"
        pass: "{{ lookup('env', 'ZAGG_PASSWORD') | default(g_default_zagg_pass, True) }}"
      pcp:
        metrics: "{{ g_default_pcp_metrics }}"
      heartbeat:
        templates: "{{ g_default_templates }}"
        hostgroups: "{{ g_default_hostgroups }}"

    g_zagg_client_cron:
    - name: run pcp checks every 5 minutes
      minute: "*/5"
      job: /usr/bin/ops-zagg-client --send-pcp
    - name: run register every 15 minutes
      minute: "*/15"
      job: /usr/bin/ops-zagg-client --send-heartbeat
    - name: run filesystem space checks every 30 minutes
      minute: "*/30"
      job: /usr/local/bin/cron-send-filesystem-metrics.sh
    - name: run create app every 5 minutes
      minute: "*/5"
      job: /usr/local/bin/cron-send-create-app.py

  pre_tasks:
  - stat:
      path: /secrets/zagg_client_vars.yml
    register: g_zagg_client_vars

  - name: Load variables that will override the defaults
    include_vars: /secrets/zagg_client_vars.yml
    when: g_zagg_client_vars.stat.exists

  - fail: "msg=This playbook requires {{ item }} to be set and not empty."
    when: "{{ item }} is not defined or not {{ item }}"
    with_items:
    - g_zagg_client_config

  - debug: var=g_zagg_client_config

  - name: Generate the zagg_client.yaml config file
    copy:
      content: "{{ g_zagg_client_config | to_nice_yaml }}"
      dest: /etc/openshift_tools/zagg_client.yaml
      mode: "644"

  - name: Setup Cron
    cron:
      name: "{{ item.name }}"
      job: "{{ item.job }}"
      minute: "{{ item.minute | default('*', True) }}"
      hour: "{{ item.hour | default('*', True) }}"
      day: "{{ item.day | default('*', True) }}"
      month: "{{ item.month | default('*', True) }}"
      weekday: "{{ item.weekday | default('*', True) }}"
    with_items: g_zagg_client_cron
