---
# These are defaults variables, override using zagg_client_vars.yml vars file
g_default_zagg_client_hostname: "UNNAMED-ZAGG-CLIENT-CTR-{{ '%05x' | format(1048576 | random) }}"
g_default_zagg_server: localhost:8000
g_default_zagg_user: admin
g_default_zagg_pass: password
g_default_zagg_ssl_verify: False
g_default_pcp_metrics:
- hinv.ncpu
- kernel.all.cpu.idle
- kernel.all.cpu.irq.hard
- kernel.all.cpu.irq.soft
- kernel.all.cpu.nice
- kernel.all.cpu.steal
- kernel.all.cpu.sys
- kernel.all.cpu.user
- kernel.all.cpu.wait.total
- kernel.all.load
- kernel.all.pswitch
- kernel.all.uptime
- kernel.uname.distro
- kernel.uname.machine
- kernel.uname.nodename
- kernel.uname.nodename
- kernel.uname.release
- kernel.uname.sysname
- kernel.uname.version
- mem.freemem
- mem.physmem
- mem.util.available
- mem.util.bufmem
- mem.util.cached
- mem.util.used
- proc.nprocs
- swap.free
- swap.length
- swap.used

g_default_hostgroups:
- Linux servers
