---

# Default to False before attempting upgrade
- set_fact: 
    update_successful:    False
    downgrade_successful: False
  when: "{{ update_needed == True }}" 

- name: Upgrade master
  command: "yum -y upgrade atomic-openshift-{{ version_wanted }} atomic-openshift-clients-{{ version_wanted }} atomic-openshift-master-{{ version_wanted }} atomic-openshift-node-{{ version_wanted }} tuned-profiles-atomic-openshift-node-{{ version_wanted }} atomic-openshift-sdn-ovs-{{ version_wanted }}"
  when: "{{ update_needed == True }}" 

- name: Check if update is successful
  command: "rpm -qa atomic-openshift"
  register: post_upgrade
  changed_when: False

# ansible will return a '17' if a match is found. '-1' means 'not found'
- name: Set update_successful=True if upgrade succeeded
  set_fact: 
    update_successful: True
  when: "{{ post_upgrade.stdout.find(version_wanted) != -1 }}"

- name: Upgrade failed, so try a downgrade
  command: "yum -y downgrade atomic-openshift-{{ version_wanted }} atomic-openshift-clients-{{ version_wanted }} atomic-openshift-master-{{ version_wanted }} atomic-openshift-node-{{ version_wanted }} tuned-profiles-atomic-openshift-node-{{ version_wanted }} atomic-openshift-sdn-ovs-{{ version_wanted }}"
  when: "{{ update_successful == False }}"

- name: Check if downgrade is successful
  command: "rpm -qa atomic-openshift"
  register: post_downgrade
  changed_when: False

# ansible will return a '17' if a match is found. '-1' means 'not found'
- name: Set downgrade_successful=True if downgrade succeeded
  set_fact: 
    downgrade_successful: True
    upgrade_successful: True
  when: "{{ post_downgrade.stdout.find(version_wanted) != -1 }}"

- name: Alert if update is not successful, but continue
  debug:
    msg: "[WARNING] The desired rpm version does not match installed version! Upgrade and downgrade failed!"
  when: "{{ update_successful == False and downgrade_successful == False }}"
  failed_when: True
  ignore_errors: True

# Note: at this point, we will have installed a new version of
# all atomic-openshift* packages. But we do *not* want to restart the node service yet!
# Restarting the node service must be done after the master's roles are reconciled.
# Otherwise the node service may fail to restart.
- name: Restart master services if upgrade was successful
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - atomic-openshift-master-api
  - atomic-openshift-master-controllers
  when: "{{ update_needed == True and upgrade_successful == True }}"

- name: Ensure master services are running
  service:
    name: "{{ item }}"
    state: running
  with_items:
  - atomic-openshift-master-api
  - atomic-openshift-master-controllers
  when: "{{ update_needed == True }}" 
  ignore_errors: True

