---
- name: Main List all templates
  zbx_template:
    zbx_server: "{{ ozb_server }}"
    zbx_user: "{{ ozb_user }}"
    zbx_password: "{{ ozb_password }}"
    state: list
  register: templates

- include_vars: template_openshift_cluster.yml
  tags:
  - clusterwide
- include_vars: template_heartbeat.yml
  tags:
  - heartbeat
- include_vars: template_os_linux.yml
  tags:
  - linux
- include_vars: template_dnsmasq.yml
  tags:
  - dnsmasq
- include_vars: template_docker.yml
  tags:
  - docker
- include_vars: template_openshift_master.yml
  tags:
  - openshift_master
- include_vars: template_openshift_master_capacity.yml
  tags:
  - openshift_master
  - openshift_master_capacity
- include_vars: template_openshift_node.yml
  tags:
  - openshift_node
- include_vars: template_ops_tools.yml
  tags:
  - ops_tools
- include_vars: template_app_zabbix_server.yml
  tags:
  - zabbix_server
- include_vars: template_app_zabbix_agent.yml
  tags:
  - zabbix_agent
- include_vars: template_performance_copilot.yml
  tags:
  - pcp
- include_vars: template_aws.yml
  tags:
  - aws
- include_vars: template_gcp.yml
  tags:
  - gcp
- include_vars: template_zagg_server.yml
  tags:
  - zagg_server

- include_vars: template_config_loop.yml
  tags:
  - config_loop

- include_vars: template_zabbix_config.yml
  tags:
  - zabbix_config

- include_vars: template_openshift_metrics.yml
  tags:
  - openshift_metrics

- include_vars: template_openshift_logging.yml
  tags:
  - openshift_logging

- include_vars: template_ops_sso.yml
  tags:
  - sso_app

- include_vars: template_clam_update.yml
  tags:
  - clam_update

- include_vars: template_psad.yml
  tags:
  - psad

- include_vars: template_multi_inventory.yml
  tags:
  - multi_inventory

- include_vars: template_config_loop_client.yml
  tags:
  - config_loop_client

- name: Include Template OpenShift Cluster
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_openshift_cluster }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - clusterwide

- name: Include Template Heartbeat
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_heartbeat }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - heartbeat

- name: Include Template os_linux
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_os_linux }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - linux

- name: Include Template dnsmasq
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_dnsmasq }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - dnsmasq

- name: Include Template docker
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_docker }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - docker

- name: Include Template Openshift Master
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_openshift_master }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - openshift_master

- name: Include Template Openshift Master Capacity
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_openshift_master_capacity }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - openshift_master
  - openshift_master_capacity

- name: Include Template Openshift Node
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_openshift_node }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - openshift_node

- name: Include Template Ops Tools
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_ops_tools }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - ops_tools

- name: Include Template App Zabbix Server
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_app_zabbix_server }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - zabbix_server

- name: Include Template App Zabbix Agent
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_app_zabbix_agent }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - zabbix_agent

- name: Include Template Performance Copilot
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_performance_copilot }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - pcp

- name: Include Template AWS
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_aws }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - aws

- name: Include Template GCP
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_gcp }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - gcp

- name: Include Template Zagg Server
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_zagg_server }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - zagg_server

- name: Include Template Config Loop
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_config_loop }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - config_loop

- name: Include Template Config Loop Client
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_config_loop_client }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - config_loop

- name: Include Template Zabbix Config
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_zabbix_config }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - zabbix_config

- name: Include Template OpenShift Metrics
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_metrics }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - openshift_metrics

- name: Include Template OpenShift Logging
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_logging }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - openshift_logging

- name: Include Template Ops SSO
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_ops_sso }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - sso_app

- name: Include Template Ops Clam Update
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_ops_clam_update }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - clam_update

- name: Include Template PSAD
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_psad }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - psad

- name: Include Template MultiInventory
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_multi_inventory }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"
  tags:
  - multi_inventory
