---
galaxy_info:
  author: OpenShift Ops
  description: rkhunter Scanning Role
  company: Red Hat, Inc
  license: ASL 2.0
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 7
dependencies:
- role: tools_roles/lib_openshift_3.2
